version: "3.8"

services:
  permanent_relay:
    image: tiarhax/michilante_dynamic_rtsp_relay:latest
    networks:
      wireguard-vpn:
          ipv4_address: 10.13.13.5
      internal-shared-network:


    env_file: dynamic_relay.env
    ports:
      - "${HTTP_PORT}:${DYNAMIC_RELAY_HTTP_PORT}"
      - "${RTSP_SERVER_PORT}:${DYNAMIC_RELAY_RTSP_PORT}"

  stalechecker:
    image: tiarhax/michilante_stale_checker:latest
    networks:
      - internal-shared-network
    env_file: stalechecker.env


networks:
  internal-shared-network:
    driver: bridge
  wireguard-vpn:
    driver: bridge
    ipam:
      config:
        - subnet: 10.13.13.0/24
