version: "3.8"

services:
  permanent-relay:
    image: tiarhax/michilante_dynamic_rtsp_relay:latest
    networks:
      - host-network
    env_file: permanent_relay.env

  pinger:
    image: tiarhax/michilante_pinger
    networks:
      - host-network

networks:
  host-network:
    driver: host
