version: "3.8"

services:
  permanent-relay:
    image: tiarhax/michilante_dynamic_rtsp_relay:latest
    networks:
      - internal-shared-network
      - host-network
    env_file: dynamic_relay.env

networks:
  internal-shared-network:
    driver: bridge
  host-network:
    driver: host
